"""Bake the weapon-down / weapon-up moves from OMFs into configs/weapons/weapon_lowered_anim.ltx and
weapon_raised_anim.ltx.

The OMF is a hands-rig motion in which only the root bone (bip01, track 0) moves. Each frame's bone
transform (rotation quaternion + translation, the same key the engine turns into the bone matrix with
mk_xform) is written out as a delta from the NORMAL (weapon up) pose, in the bone's own frame, and
CWeapon::UpdateLoweredPose layers it additively on bip01:
  - the way down (weapon_lowered.omf): frame 0 = up, last frame = down -> --ref first (the default)
  - the way up   (weapon_raised.omf):  frame 0 = down, last frame = up -> --ref last
Without a way-up animation the engine plays the way down backwards.

    python tools/omf_to_lowered.py <weapon_lowered.omf> <out .ltx> [track, default 0] [fps, default 30]
    python tools/omf_to_lowered.py <weapon_raised.omf> <out .ltx> --section weapon_raised_anim --ref last

Handles both OMF parameter layouts: with bone names (name + u32 per bone) and without them (u32 per bone),
which is what a hands-rig export writes.
"""
import struct, sys, math, argparse


def chunks(d):
    out, p = {}, 0
    while p + 8 <= len(d):
        cid, sz = struct.unpack_from('<II', d, p)
        out[cid & 0x7FFFFFFF] = d[p + 8:p + 8 + sz]
        p += 8 + sz
    return out


def read_tracks(path):
    d = open(path, 'rb').read()
    c = chunks(d)
    ms = c[14]
    sub, p = [], 0
    while p + 8 <= len(ms):
        cid, sz = struct.unpack_from('<II', ms, p)
        sub.append(ms[p + 8:p + 8 + sz]); p += 8 + sz
    m = sub[1]
    e = m.index(b'\0'); name = m[:e].decode('latin1'); q = e + 1
    n = struct.unpack_from('<I', m, q)[0]; q += 4
    tracks = []
    while q < len(m):
        fl = m[q]; q += 1
        if fl & 2:
            R = [struct.unpack_from('<4h', m, q)] * n; q += 8
        else:
            q += 4; R = [struct.unpack_from('<4h', m, q + 8 * i) for i in range(n)]; q += 8 * n
        keys = None
        if fl & 1:
            q += 4; w, fmt = (6, '<3h') if fl & 4 else (3, '<3b')
            keys = [struct.unpack_from(fmt, m, q + w * i) for i in range(n)]; q += w * n
            size = struct.unpack_from('<3f', m, q); q += 12
        init = struct.unpack_from('<3f', m, q); q += 12
        T = [tuple(k * s + i for k, s, i in zip(kk, size, init)) for kk in keys] if keys else [init] * n
        Q = [tuple(v / 32767.0 for v in r) for r in R]
        tracks.append((T, Q))
    assert q == len(m), 'track data does not end where the motion chunk does'
    return name, n, tracks


def qmul(a, b):
    ax, ay, az, aw = a; bx, by, bz, bw = b
    return (aw * bx + ax * bw + ay * bz - az * by,
            aw * by - ax * bz + ay * bw + az * bx,
            aw * bz + ax * by - ay * bx + az * bw,
            aw * bw - ax * bx - ay * by - az * bz)


def qnorm(a):
    l = math.sqrt(sum(v * v for v in a)) or 1.0
    return tuple(v / l for v in a)


def qrot(q, v):
    """rotate v by unit quaternion q (x, y, z, w)"""
    p = qmul(qmul(q, (v[0], v[1], v[2], 0.0)), (-q[0], -q[1], -q[2], q[3]))
    return p[:3]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('src'); ap.add_argument('out')
    ap.add_argument('track', nargs='?', type=int, default=0)
    ap.add_argument('fps', nargs='?', type=float, default=30.0)
    ap.add_argument('--section', default='weapon_lowered_anim')
    ap.add_argument('--ref', choices=('first', 'last'), default='first',
                    help='the frame that is the normal (weapon up) pose: first for the way down, last for the way up')
    a = ap.parse_args()
    src, out, track, fps = a.src, a.out, a.track, a.fps
    name, n, tracks = read_tracks(src)
    T, Q = tracks[track]
    moving = [i for i, (t, q) in enumerate(tracks) if len(set(t)) > 1 or len(set(q)) > 1]
    print(f'{src}: motion "{name}", {n} frames, {len(tracks)} tracks, moving: {moving}, baking track {track}')
    # relative to the normal-pose frame (identity in a clean export, but do not rely on it)
    r = 0 if a.ref == 'first' else n - 1
    q0 = qnorm(Q[r]); q0i = (-q0[0], -q0[1], -q0[2], q0[3]); t0 = T[r]
    lines = ['; GENERATED by tools/omf_to_lowered.py -- do not edit by hand, re-run the script instead.',
             f'; source: {src}',
             f'; motion "{name}", track {track}, {n} frames at {fps:g} fps; per frame: tx, ty, tz, qx, qy, qz, qw',
             f'; (the bone\'s transform relative to frame {r} -- the weapon-up pose -- in its own frame, layered additively',
             ';  on bip01 by CWeapon::UpdateLoweredPose)',
             '',
             f'[{a.section}]',
             f'fps\t\t= {fps:g}',
             f'frames\t= {n}']
    for i in range(n):
        # delta in the bone's own frame = inverse(M(r)) * M(i): rotation q0^-1 q(i),
        # translation q0^-1 (T(i) - T0) -- the engine applies it additively on the bone (bip01)
        q = qnorm(qmul(q0i, Q[i]))
        t = qrot(q0i, tuple(a - b for a, b in zip(T[i], t0)))
        lines.append(f'f{i}\t\t= {t[0]:.5f}, {t[1]:.5f}, {t[2]:.5f}, {q[0]:.5f}, {q[1]:.5f}, {q[2]:.5f}, {q[3]:.5f}')
    open(out, 'wb').write(('\r\n'.join(lines) + '\r\n').encode('ascii'))
    print(f'written {out}')


if __name__ == '__main__':
    main()
